export const product_list = [
  {
    title: "Green Table",
    price: 500,
    location: "Haifa",
    img: "https://negativespace.co/wp-content/uploads/2024/04/negative-space-girl-in-skirt-on-golf-course-768x1152.jpg",
  },
  {
    title: "Blue Chair",
    price: 250,
    location: "Tel Aviv",
    img: "https://negativespace.co/wp-content/uploads/2024/04/negative-space-sunset-beach-wallpaper-1536x1023.jpg",
  },
  {
    title: "Red Sofa",
    price: 1200,
    location: "Jerusalem",
    img: "https://negativespace.co/wp-content/uploads/2024/04/negative-space-palm-trees-evening-03-944x708.jpg",
  },
  {
    title: "White Desk",
    price: 800,
    location: "Beersheba",
    img: "https://www.shutterstock.com/shutterstock/photos/2237579873/display_1500/stock-photo-high-detail-medium-portrait-photo-a-mongolian-man-in-a-traditional-hat-looking-at-the-camera-2237579873.jpg",
  },
  {
    title: "Yellow Lamp",
    price: 120,
    location: "Eilat",
    img: "https://www.shutterstock.com/shutterstock/photos/2230331327/display_1500/stock-photo-ornate-mecha-turkey-thanksgiving-k-high-quality-render-multicolor-vivid-2230331327.jpg",
  },
  {
    title: "Gray Bookshelf",
    price: 450,
    location: "Netanya",
    img: "https://www.shutterstock.com/shutterstock/photos/2451944835/display_1500/stock-photo-create-a-graphic-novel-illustration-that-is-set-in-the-philippines-in-the-province-of-albay-in-2451944835.jpg",
  },
  {
    title: "Black Coffee Table",
    price: 300,
    location: "Ashdod",
    img: "https://www.shutterstock.com/shutterstock/photos/2438857311/display_1500/stock-photo-old-school-cabover-big-rig-truck-with-slammed-suspension-on-a-highway-to-hell-with-lightning-2438857311.jpg",
  },
  {
    title: "Purple Armchair",
    price: 650,
    location: "Rishon LeZion",
    img: "https://www.shutterstock.com/shutterstock/photos/2454534503/display_1500/stock-photo-space-ships-eyeballs-aliens-planets-objects-dancers-people-animals-vehicles-swirling-in-a-2454534503.jpg",
  },
  {
    title: "Orange Ottoman",
    price: 180,
    location: "Petah Tikva",
    img: "https://www.shutterstock.com/shutterstock/photos/2455784525/display_1500/stock-photo-japanese-god-man-colors-storm-cyclone-photo-realistic-wind-detailed-2455784525.jpg",
  },
  {
    title: "Brown TV Stand",
    price: 550,
    location: "Rehovot",
    img: "https://www.shutterstock.com/shutterstock/photos/2422989321/display_1500/stock-photo-advertising-product-photo-of-draw-me-people-during-a-puppy-yoga-activity-2422989321.jpg",
  },
  {
    title: "Ivory Dining Table",
    price: 1500,
    location: "Nahariya",
    img: "https://www.shutterstock.com/shutterstock/photos/2438948135/display_1500/stock-photo-advertising-testimonial-photo-of-houston-skyline-2438948135.jpg",
  },
  {
    title: "Navy Recliner",
    price: 700,
    location: "Karmiel",
    img: "https://www.shutterstock.com/shutterstock/photos/2341522131/display_1500/stock-photo-wet-plate-photo-of-three-men-stand-on-top-of-the-giant-stack-of-books-on-the-ocean-a-small-beer-2341522131.jpg",
  },
  {
    title: "Fuchsia Loveseat",
    price: 900,
    location: "Tiberias",
    img: "https://www.shutterstock.com/shutterstock/photos/2341979631/display_1500/stock-photo-create-a-photo-of-a-cappuccino-with-an-image-of-a-brain-on-the-top-2341979631.jpg",
  },
  {
    title: "Sage Chaise Lounge",
    price: 1100,
    location: "Nazareth",
    img: "https://www.shutterstock.com/shutterstock/photos/2400550787/display_1500/stock-photo-close-up-photo-of-graphic-design-vector-bright-and-colorful-very-detailed-high-quality-a-funny-2400550787.jpg",
  },
  {
    title: "Teal Nightstand",
    price: 220,
    location: "Ra'anana",
    img: "https://www.shutterstock.com/shutterstock/photos/2293486833/display_1500/stock-photo-close-up-photo-of-lord-vishnu-sleeping-on-snake-with-laxmi-2293486833.jpg",
  },
  {
    title: "Maroon Dresser",
    price: 950,
    location: "Beit Shemesh",
    img: "https://www.shutterstock.com/shutterstock/photos/2336493001/display_1500/stock-photo-cyberpunk-photo-of-a-handshake-2336493001.jpg",
  },
  {
    title: "Lime Stool",
    price: 80,
    location: "Kiryat Shmona",
    img: "https://www.shutterstock.com/shutterstock/photos/2369301055/display_1500/stock-photo-rural-country-setting-photo-quality-s-picture-of-small-modest-farmhouse-with-small-porch-in-2369301055.jpg",
  },
  {
    title: "Cherry Accent Chair",
    price: 450,
    location: "Bat Yam",
    img: "https://www.shutterstock.com/shutterstock/photos/2418655625/display_1500/stock-photo-advertising-podium-photo-of-three-fan-on-podium-cool-blue-wind-plants-and-spotlight-2418655625.jpg",
  },
];
